### ISSUE TITLE
Error in ls(envir = envir, all.names = private) :    invalid 'envir' argument

### ISSUE THREAD

**Issue by swhalen98** [rpremraj/mailR#19] opened 2015-03-17 19:50 UTC
Sorry I know this question has been asked multiple times. I am not behind a corp firewall and I turned off 2 step verification in gmail.

> library(mailR)
> send.mail(from = "AAAA@gmail.com",
+           to = "BBBB@gmail.com",
+           subject = "Subject of the email",
+           body = "Body of the email",
+           smtp = list(host.name = "smtp.gmail.com", port = 465, user.name = "AAAA", passwd = "CCCC", ssl = TRUE),
+           authenticate = TRUE,
+           debug = TRUE,
+           send = TRUE)
Error in ls(envir = envir, all.names = private) : 
  invalid 'envir' argument
> traceback()
23: ls(envir = envir, all.names = private)
22: getFields.Object(x, ...)
21: getFields(x, ...)
20: names.Object(x)
19: names(x)
18: match(x, table, nomatch = 0L)
17: name %in% names(x)
16: `$.Throwable`(c, "message")
15: c$message
14: conditionMessage.condition(cond)
13: conditionMessage(cond)
12: stop(list(message = "org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:465", 
        call = .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", 
            cl, .jcast(if (inherits(o, "jobjRef") || inherits(o, 
                "jarrayRef")) o else cl, "java/lang/Object"), .jnew("java/lang/String", 
                method), j_p, j_pc, use.true.class = TRUE, evalString = simplify, 
            evalArray = FALSE), jobj = <S4 object of class "jobjRef">))
11: .Call(RJavaCheckExceptions, silent)
10: .jcheck(silent = FALSE)
9: .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl, 
       .jcast(if (inherits(o, "jobjRef") || inherits(o, "jarrayRef")) o else cl, 
           "java/lang/Object"), .jnew("java/lang/String", method), 
       j_p, j_pc, use.true.class = TRUE, evalString = simplify, 
       evalArray = FALSE)
8: .jrcall(x, name, ...)
7: email$send()
6: doTryCatch(return(expr), name, parentenv, handler)
5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
4: tryCatchList(expr, classes, parentenv, handlers)
3: tryCatch(..., Throwable = function(e) {
       if (!is.jnull(e$jobj)) {
           print(e$jobj$printStackTrace())
           stop(paste(class(e)[1], e$jobj$getMessage(), sep = " (Java): "), 
               call. = FALSE)
       }
       else stop("Undefined error occurred! Turn debug mode on to see more details.")
   })
2: .jTryCatch(email$send())
1: send.mail(from = "AAAA@gmail.com", to = "BBBB@gmail.com", 
       subject = "Subject of the email", body = "Body of the email", 
       smtp = list(host.name = "smtp.gmail.com", port = 465, user.name = "AAAA", 
           passwd = "CCCC", ssl = TRUE), authenticate = TRUE, 
       debug = TRUE, send = TRUE)
>

**Comment by luisd303** [comment] 2015-03-24 01:24
I was having this issue. I resolved it by updating Java. 1.7 worked. 1.5 didn't.

**Comment by swhalen98** [comment] 2015-04-03 15:34
I am using Java 1.8 - Do you think that might be an issue?

**Comment by rpremraj** [comment] 2015-05-02 15:08
Is this issue fixed now, or do you still need support?

**Comment by swhalen98** [comment] 2015-05-02 16:27
I'm still having the error



On May 2, 2015, at 11:08 AM, Rahul Premraj <notifications@github.com> wrote:

Is this issue fixed now, or do you still need support?

**Comment by aoyh** [comment] 2015-05-12 08:02
This issue occurred to me as well. Somehow, under the same environment, it sometimes works, and one minute later it doesn't, which might suggest a root cause of network communication stability.

Here is what is printed using `debug = TRUE` when it is not working:
```
DEBUG: successfully loaded resource: /META-INF/javamail.default.address.map
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
DEBUG SMTP: need username and password for authentication
DEBUG SMTP: useEhlo true, useAuth true
DEBUG SMTP: trying to connect to host "smtp.gmail.com", port 465, isSSL false
Error in ls(envir = envir, all.names = private) : 
  invalid 'envir' argument
```
So far, I did not find an ultimate solution for it. If anyone knows, please kindly give some light.

My workaround is a little perseverance. Say, I want to keep trying for 5 minutes, calling it 30 times, with 10 seconds break in between each unsuccessful attempt. My codes are as follows:
```
MailIt <- function(x) {
  tryCatch(
    {send.mail(..., debug = TRUE); ok <<- TRUE}, 
	error = function(e) {i <<- i + 1; Sys.sleep(10)}
  )
}
  
i <- 1
ok <- FALSE
while (i <= 30 & ok == FALSE) MailIt()
```
Of course, the bad luck is that it won't work even trying 30 times...

**Comment by rpremraj** [comment] 2015-06-19 19:58
@swhalen98 Did you try enabling SMTP access for gmail here: https://www.google.com/settings/security/lesssecureapps?

**Comment by swhalen98** [comment] 2015-06-19 20:13
Yes - I enabled SMTP access for gmail to make sure I would not be caught up
in a verification issue.

**Comment by rpremraj** [comment] 2015-12-06 21:05
Try installing the latest version of mailR from GitHub. I am curious to see whether the changes will result in a more descriptive error message. Thx!

**Comment by rpremraj** [comment] 2016-07-05 19:23
No activity on this thread... presuming issue resolved.

**Closed by rpremraj** 2016-07-05 19:23 UTC
